################################################################################
#                         Iosevka Private Build Plans                          #
################################################################################

#               Customize this file with your custom parameters.               #
#              These can be obtained by using the font builder in              #
#                   <https://typeof.net/Iosevka/customizer>                    #

################################################################################
# Sans-Serif Variants
################################################################################

[buildPlans.iosevka-term]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-term.variants.design]
g = "double-storey"
l = "serifed-flat-tailed"
asterisk = "penta-low"
underscore = "above-baseline"
ampersand = "upper-open"
bar = "force-upright"
lig-neq = "slightly-slanted-dotted"

[buildPlans.iosevka-term.ligations]
inherits = "default-calt"
disables = ['eqeq', 'exeq']     # Disables '==', '===', '!=', '!==' ligations

[buildPlans.iosevka-term.variants.italic]
g = "single-storey-serifless"
q = "diagonal-tailed-serifless"

[buildPlans.iosevka-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-term.weights.bold]
shape = 700
menu = 700
css = 700

################################################################################

[buildPlans.iosevka-fixed]
family = "Iosevka Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-fixed.variants.design]
g = "double-storey"
l = "serifed-flat-tailed"
asterisk = "penta-low"
underscore = "above-baseline"
ampersand = "upper-open"
bar = "force-upright"
lig-neq = "slightly-slanted-dotted"

[buildPlans.iosevka-fixed.variants.italic]
g = "single-storey-serifless"
q = "diagonal-tailed-serifless"

[buildPlans.iosevka-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-fixed.weights.bold]
shape = 700
menu = 700
css = 700

